# Generated by Django 4.2.11 on 2024-04-15 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_media_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='cerated',
            new_name='created',
        ),
    ]
