# Generated by Django 4.2.11 on 2024-04-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='subsection',
            field=models.CharField(choices=[('important', 'Важные темы'), ('common', 'Обычные темы')], default='common', max_length=20, verbose_name='Подраздел'),
        ),
    ]
